call npm i grapesjs-plugin-export
call  npm i grapesjs-plugin-filestack
call npm i grapesjs-plugin-ckeditor
call npm i grapesjs-aviary
call npm i grapesjs-blocks-basic
call npm i grapesjs-plugin-forms
call npm i grapesjs-navbar
call npm i grapesjs-component-countdown
call npm i grapesjs-style-gradient